### ISSUE TITLE
Nesting Modules not working properly

### ISSUE THREAD

**Issue by visualcookie** [getkirby-plugins/modules-plugin#6]
I have two modules. A "row module" and a "column module". Both are in site/modules.

Got he following blueprints for them:

`gridrow.yml`
``` yml
title: Row Module
pages:
  template:
    - module.gridrow
    - module.gridcolumn
  build:
    - title: _modules
      uid: modules
      template: modules
fields:
  title:
    label: Module Title
    type: text
  modules:
    label: Modules
    type: modules

  moduleSettings:
    label: Module Settings
    type: headline
  gridmodifiers:
    label: Grid Modifiers
    type: text
```

`gridcolumn.yml`
``` yml
title: Column Module
pages: false
files: false
icon: columns

fields:
  title:
    label: Module Title
    type: text

  text:
    label: Text
    type: textarea

  moduleSettings:
    label: Module settings
    type: headline
  column:
    label: Column
    type: select
    default: 12/12
    options:
      12/12: One
      6/12: Two
      4/12: Three
      3/12: Four
    width: 1/2
  column_mobile:
    label: Column Mobile
    type: select
    default: 6/12
    options:
      12/12: One
      6/12: Two
      4/12: Three
      3/12: Four
    width: 1/2
```

Now what should happen is, that when I go in my Row Module and want to add a new module there but I can't select my modules templates.
